Document: dockerplugin
Title: Debian dockerplugin Manual
Author: <insert document author here>
Abstract: This manual describes what dockerplugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dockerplugin/dockerplugin.sgml.gz

Format: postscript
Files: /usr/share/doc/dockerplugin/dockerplugin.ps.gz

Format: text
Files: /usr/share/doc/dockerplugin/dockerplugin.text.gz

Format: HTML
Index: /usr/share/doc/dockerplugin/html/index.html
Files: /usr/share/doc/dockerplugin/html/*.html
